entries/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url, include
from entries.models import Entry, News
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView

info_dict = {
    'queryset': Entry.objects.all(),
}

urlpatterns = patterns('',
                       # select
                       (r'^$', ListView.as_view(queryset=News.objects.all())),
                       # BBS
                       # create
                       (r'^create/$',
                        CreateView.as_view(model=Entry, success_url='/entries/bbs/')),
                       # edit
                       (r'^detail/(?P<pk>\d+)/$',
                        DetailView.as_view(queryset=Entry.objects.all())),
                       # update
                       (r'^update/(?P<pk>\d+)/$',
                        UpdateView.as_view(model=Entry)),
                       # delete
                       (r'^delete/(?P<pk>\d+)/$',
                        DeleteView.as_view(model=Entry, success_url='/entries/bbs/')),
                       # NEWS
                       # create
                       (r'^create_news/$',
                        CreateView.as_view(model=News, success_url='/entries/')),
                       # edit
                       (r'^detail_news/(?P<pk>\d+)/$',
                        DetailView.as_view(queryset=News.objects.all())),
                       # update
                       (r'^update_news/(?P<pk>\d+)/$',
                        UpdateView.as_view(model=News)),
                       # delete
                       (r'^delete_news/(?P<pk>\d+)/$',
                        DeleteView.as_view(model=News, success_url='/entries/')),

                       # normal pages
                       (r'^mail/', TemplateView.as_view(template_name="pages/mail.html")),
                       (r'^member/', TemplateView.as_view(template_name="pages/member.html")),
                       (r'^bbs/', ListView.as_view(queryset=Entry.objects.all())),
                       (r'^schedule/', TemplateView.as_view(template_name="pages/schedule.html")),
                       (r'^master/', TemplateView.as_view(template_name="pages/master.html")),
                       (r'^links/', TemplateView.as_view(template_name="pages/links.html")),
                       (r'^edogawa/', TemplateView.as_view(template_name="pages/edogawa.html")),
                       (r'^shinjukuclub/', TemplateView.as_view(template_name="pages/shinjukuclub.html")),
                       (r'^mail/', TemplateView.as_view(template_name="pages/mail.html")),
                       # comment for BBS
                       (r'^comments/', include('django.contrib.comments.urls')),
                       # base.htmlのプルダウン言語セットに必須
                       (r'^i18n/', include('django.conf.urls.i18n')),
)

# login / logout
urlpatterns += patterns('',
                        (r'login/$', 'django.contrib.auth.views.login',
                         {'template_name': 'entries/registration/login.html'}),
                        (r'^logout/$',
                         'django.contrib.auth.views.logout',
                         {'template_name': 'entries/registration/logout.html'}),
)

jam/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # スラッシュだけで行けるよう
                       url(r'^$', include('entries.urls')),
                       url(r'^entries/', include('entries.urls')),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)',
                             'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT,
                              'show_indexes': True}),
                            # {'document_root': settings.MEDIA_URL +
                            # {'document_root' : os.path.dirname(__file__) +
                            # '/static'}),
    )

entries/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
class Entry(models.Model):
    """
    エントリのモデル
    """
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.EmailField(help_text='A valid e-mail address, please.')
    content = models.TextField(max_length=1000)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/entries/detail/%i" % self.id


class News(models.Model):
    """
    ニュース
    """
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    date = models.DateField(max_length=None)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/entries/detail_news/%i" % self.id


class Comment(models.Model):
    """
    エントリに対するコメントのモデル
    """
    # スレッド
    entry = models.ForeignKey(Entry, verbose_name=u'スレッド')
    name = models.CharField(max_length=100, verbose_name=u'名前')
    email = models.EmailField(help_text='A valid e-mail address, please.')
    # メッセージ
    message = models.CharField(u'メッセージ', max_length=200, blank=False)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'コメント'

    def __unicode__(self):
        return self.message

    def get_absolute_url(self):
        return "/entries/detail/%i" % self.id

entries/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
from django.forms import ModelForm
from entries.models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ('entry', )

entries/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import render_to_response, get_object_or_404
from entries.models import Entry, Comment
from entries.forms import CommentForm
# TODO: 今後使う？
from django.http import HttpResponse, Http404
from django.utils.translation import get_language, activate, ugettext_lazy as _


class EntryView(ListView):
    context_object_name = "object_list"
    queryset = Entry.objects.all()


class EntryDetailView(DetailView):
    queryset = Entry.objects.all()
    model = Entry

    def get_object(self):
        """
        :return:
        """
        # Call the superclass
        object = super(EntryDetailView, self).get_object
        # Record the last accessed date
        # object.last_accessed = timezone.now()
        # object.save()
        # Return the object
        return object

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['comment_list'] = Comment.objects.all()
        return context


def entry_detail(request, entry_id):
    '''
    指定したスレッドを表示する。
    参考
    http://www.gesource.jp/programming/python/django/t002.html
    :param request: リクエスト
    :param entry_id: エントリID
    '''
    # 表示するエントリ
    entry = get_object_or_404(Entry, pk=entry_id)

    # コメントの登録処理
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # コメントを登録
            comment = form.save(cosmmit=False)
            comment.thread = entry
            comment.save()
            form = CommentForm()  # フォームの初期化
    else:
        form = CommentForm()
    # スレッドのコメント
    comment_list = entry.comment_set.all().order_by('id')
    return TemplateView.as_view(template_name='entries/entry_detail.html',
                                extra_context=
                                {'object': entry,
                                 'comment_list': comment_list,
                                 'form': form})

entries/templates/comments/form.html
{% load comments %}
{#% load markup %#}
{% load i18n %}

{% block title %}Preview Comment{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
   {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
    {% if form.errors %}
    <h2>{% blocktrans count form.errors|length as counter %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h2>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
    <table> 
    {% for field in form %}
      {% if field.is_hidden %}
        <tr><td>{{ field }}</td></td></tr>
       {% else %}
        {% if field.errors %}<tr><td colspan="2">{{ field.errors }}</td></tr>{% endif %}
          <tr{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}><td>{{ field.label_tag }}</td><td>{{ field }}</td></tr>
      {% endif %}
    {% endfor %}
    </table>    
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </form>
{% endblock %}

entries/templates/comments/posted.html
{% extends "entries/base_entries.html" %}

{% block entry_content %}
{% load comments %}

{% block title %}Comment Posted{% endblock %}

{% block content %}
<h2 class="title">Comment Posted</h2>
<div class="post">
<div class="entry">
<p>Your comment was posted succesfully
{% if comment.is_public %}
 - you can see it by <a href="{{comment.content_object.get_absolute_url}}">returning to the post</a>.
{% else %}
 - it has been held for moderation and, if deemed appropriate, will be approved in due course.
{% endif %}
</p>
</div> 
</div>
{% endblock %}
{% endblock %}

entries/templates/comments/preview.html
{% extends "entries/base_entries.html" %}
{% load comments %}
{#% load markup %#}
{% load i18n %}

{% block entry_content %}
{% block title %}Preview Comment{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
   {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
    {% if form.errors %}
    <h2>{% blocktrans count form.errors|length as counter %}Please correct the error below{% plural %}Please correct the errors below{% endblocktrans %}</h2>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
<table> 
    {% for field in form %}
      {% if field.is_hidden %}
        <tr><td>{{ field }}</td></td></tr>
       {% else %}
        {% if field.errors %}<tr><td colspan="2">{{ field.errors }}</td></tr>{% endif %}
          <tr{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}><td>{{ field.label_tag }}</td><td>{{ field }}</td></tr>
      {% endif %}
    {% endfor %}
</table>    
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </form>
{% endblock %}
{% endblock %}

entries/templates/entries/base_entries.html
{% extends "base.html" %}
{% block main %}
<div id="contents">

<h3>掲示板</h3>
<hr />
{% block entry_content %}
{% endblock entry_content %}

<hr />
</div>
{% endblock main %}

entries/templates/entries/entry_confirm_delete.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}

{# if not user.is_anonymous #}
<form method="post" action="." accept-charset="utf-8">{% csrf_token %}
  <p>削除します。よろしいですか？</p><br />

  <input type="submit" />
  <input type="button" value="いいえ" onClick="location.href='/entries/'" />
</form>
<br />
{# endif #}
{% endblock %}

entries/templates/entries/entry_detail.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}
<dt>
  <b>{{ object.title }}</b>
</dt>

<dd>
  {{ object.content }}
</dd>
<dd div class="operation">
  [<a href="/entries/update/{{ object.id }}">編集</a>]
  [<a href="/entries/delete/{{ object.id }}">削除</a>]
</dd>

<hr />
{% for comment in comment_list %}
  <li>
    {{ comment.message }}<br />
    ({{ comment.pub_date|date:"Y年m月d日h時i分s秒" }})
  </li>
{% endfor %}

{% load comments %}
<h2><a name="comments" href="#"></a>Comments</h2>
{% get_comment_list for object as comment_list %}
{% for comment in comment_list %}
<p class="date">On {{comment.submit_date|date:"F j,Y" }}, {{ comment.user_name}} said:</p>
<blockquote>
{{comment.comment}}
</blockquote>
{% endfor %}

<div id="add_comment">
<h2>コメント追加</h2>
{% render_comment_form for object %}
</div>

{% endblock %}

entries/templates/entries/entry_form.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}

{% if object %}
<h3>編集</h3><br />
{% else %}
<h3>新規作成</h3><br />
{% endif %}

{% if form.has_errors %}
  {% for field in form.fields %}
    {% if fields.error %}
      {{ field.error}}
    {% endif %}

  {% endfor %}
{% endif %}

<div class="validation">
  <form action="." method="post" accept-charset="utf-8">{% csrf_token %}
    <label for="id_title">タイトル</label>{{ form.title }}
    {% if form.title.errors %}
    <p>
      <error> {{ form.title.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_email">e-mail</label>{{ form.email }}
    {% if form.email.errors %}
    <p>
      <error> {{ form.email.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_name">Name</label>{{ form.name }}
    {% if form.name.errors %}
    <p>
      <error> {{ form.name.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_enable_comments">Comment</label>{{ form.enable_comments }}
    {% if form.enable_comments.errors %}
    <p>
      <error> {{ form.enable_comments.errors|join:", " }}</error>
    </p>
    {% endif %}
    <br/><br/>

    <label for="id_content">内容</label>{{ form.content }}
    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    <br />
    {% endif %}
    <p><input type="submit" value="保存" /></p><br />
  </form>
</div>
{% endblock %}

entries/templates/entries/entry_list.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}

<!-- BBS一覧 -->
{% if object_list.count < 1 %}
  <b>投稿された記事はありません。</b>
{% else %}
  {# ここからページネーションの開始 #}
  {% load pagination_tags %}
  {% autopaginate object_list 12 %}

  {# 数字表示 #}
  {% paginate %}
  {% for entry in object_list %}
  <dt>
    [{{ entry.id }}] <b><a href="/entries/detail/{{ entry.id }}">{{ entry.title }}</a></b>
    by {{ entry.name }}
    [<a href="mailto:{{ entry.email }}">mail</a>]
    [投稿日: {{ entry.create_at }}]
  </dt>

  <dd>
    {{ entry.content }}
  </dd>

  <dd class="operation">
    [<a href="/entries/update/{{ entry.id }}">編集</a>]
    [<a href="/entries/delete/{{ entry.id }}">削除</a>]
  </dd>
  <hr />
  {% endfor %}

  {# 数字表示 #}
  {% paginate %}
{% endif %}
<dd div class="operation">
  [<a href="/entries/create/">記事の追加</a>]
</dd>
{% endblock %}

entries/templates/entries/news_confirm_delete.html
{% extends "pages/index.html" %}
{% block news_content %}

{% if not user.is_anonymous %}
<form method="post" action="." accept-charset="utf-8">{% csrf_token %}
  <p>削除します。よろしいですか？</p><br />

  <input type="submit" />
  <input type="button" value="いいえ" onClick="location.href='/entries/'" />
</form>
<br />
{% endif %}
{% endblock %}

entries/templates/entries/news_detail.html
{% extends "pages/index.html" %}
{% block news_content %}

<dt>
  {{ objec.title }}
</dt>
<dd>
  {{ object.content|linebreaks }}
</dd>
<dd>
  -
  {{ object.date }}
  {% if news.date|date:"w" == '0' %}
  {# 日曜 #}
  (<font color="#FF0000">{{ news.date|date:"D" }}</font>)
  {% elif news.date|date:"w" == '6' %}
  {# 土曜 #}
  (<font color="#0000FF">{{ news.date|date:"D" }}</font>)
  {% else %}
  (<font color="#000000">{{ news.date|date:"D" }}</font>)
  {% endif %}
</dd>
</br />

<dd div class="operation">
  [<a href="/entries/update_news/{{ object.id }}">編集</a>]
  [<a href="/entries/delete_news/{{ object.id }}">削除</a>]
</dd>
<br />
{% endblock %}

entries/templates/entries/news_form.html
{% extends "pages/index.html" %}
{% block news_content %}

{% for news in object_list %}
  <div>
    <img src="{{ STATIC_URL }}img/box.gif" width=10 height=10>
    <a href="/entries/detail_news/{{ news.id }}">{{ news.title }}</a>
    - {{ news.date }}
    {% if news.date|date:"w" == '0' %}
    {# 日曜 #}
    (<font color="#FF0000">{{ news.date|date:"D" }}</font>)
    {% elif news.date|date:"w" == '6' %}
    {# 土曜 #}
    (<font color="#0000FF">{{ news.date|date:"D" }}</font>)
    {% else %}
    (<font color="#000000">{{ news.date|date:"D" }}</font>)
    {% endif %}
    [<a href="/entries/update_news/{{ news.id }}">編集</a>]
    [<a href="/entries/delete_news/{{ news.id }}">削除</a>]
  </div>
  <hr />
{% endfor %}

{% if object %}
<h3>編集</h3><br />
{% else %}
<h3>新規作成</h3><br />
{% endif %}

{% if form.has_errors %}
  {% for field in form.fields %}
    {% if fields.error %}
      {{ field.error}}
    {% endif %}

  {% endfor %}
{% endif %}

<div class="validation">
  <form action="." method="post" accept-charset="utf-8">{% csrf_token %}
    <!-- タイトル -->
    <label for="id_title">タイトル：</label>{{ form.title }}
    {% if form.title.errors %}
    <p>
      <error> {{ form.title.errors|join:", "}}</error>
    </p>
    {% endif %}
    <br/><br/>
    <!-- 内容 -->
    <label for="id_content">内容：</label>{{ form.content }}
    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    {% endif %}
    <br /><br />
    <!-- 日付 -->
    <!-- 
    <label for="id_date">日付：</label>{{ form.date }}
    --> 
    <p><label for="id_date">日付:</label><input value="{{form.date.value|date:"c"}}" id="id_date" name="date" type="text" class="jquery-ui-datepicker"/></p>

    {% if form.content.errors %}
    <p>
      <error>
      {{ form.content.errors|join:", " }}
      </error>
    </p>
    <br /><br />
    {% endif %}
    <p><input type="submit" value="保存" /></p><br />
  </form>
</div>
{% endblock %}

entries/templates/entries/news_list.html
{% extends "pages/index.html" %}
{% block news_content %}

{# お知らせ #}
{% if object_list.count < 1 %}
  <b>投稿されたお知らせはありません。</b>
  <br />
{% else %}
  {# ここからページネーションの開始 #}
  {% load pagination_tags %}
  {% autopaginate object_list 12 %}

  {# 数字表示 #}
  {% paginate %}
  {% for news in object_list %}
  <div>
    <img src="{{ STATIC_URL }}img/box.gif" width=10 height=10>
    <a href="/entries/detail_news/{{ news.id }}">{{ news.title }}</a>
    - {{ news.date }}
    {% if news.date|date:"w" == '0' %}
    {# 日曜 #}
    (<font color="#FF0000">{{ news.date|date:"D" }}</font>)
    {% elif news.date|date:"w" == '6' %}
    {# 土曜 #}
    (<font color="#0000FF">{{ news.date|date:"D" }}</font>)
    {% else %}
    (<font color="#000000">{{ news.date|date:"D" }}</font>)
    {% endif %}

    {% if not user.is_anonymous %}
      [<a href="/entries/update_news/{{ news.id }}">編集</a>]
      [<a href="/entries/delete_news/{{ news.id }}">削除</a>]
    {% endif %}
  </div>
  <hr />
  {% endfor %}

  {# 数字表示 #}
  {% paginate %}
  {# ここまでページネーションの開始 #}
{% endif %}

{# 管理者限定 #}
{% if not user.is_anonymous %}
<p>[<a href="/entries/create_news/">記事の追加</a>]</p>
<!--input id="add_news" type="button" value="記事の追加"></input-->
{% endif %}

<div id="glr1"></div>
{% endblock %}

entries/templates/pages/bbs.html
{% extends "entries/base_entries.html" %}
{% block entry_content %}
  <ul id="nav">
  </ul>
{% endblock %}

entries/templates/pages/edogawa.html
{% extends "base.html" %}
{% block main %}
   <!-- コンテンツ内部 -->
   <div id="contents">
      <img src="{{ STATIC_URL }}img/tkdban.jpg" width="580" height="200" /><br />
      <br />
      {% load i18n %}
      <h2>{% trans 'edogawaclub' %}{% trans 'training' %}</h2>
      <br />
      <a href="http://www.city.edogawa.tokyo.jp/shisetsuguide/bunya/kuyakusho/kuminkan/c_toubu/guide/index.html" target="_blank">江戸川クラブの地図はこちらです。</a> 
      <br />
      <table width="580" align="center" cellpadding="1" cellspacing="1" bgcolor="#CCCCCC">
         <tr bgcolor="#FFFFCC">
            <td width="1026">
               <div align="center"><strong>&gt;&gt; {% trans 'edogawaclub' %} &lt;&lt;
                  </strong>
               </div>
            </td>
         </tr>
         <tr>
            <td height="113" bgcolor="#FFFFFF">{% trans 'every thursday' %}(月４回) <br />
               {% trans 'time' %}: １７：３０～１８：３０<br />
               {% trans 'place' %}: 江戸川区東部区民館　(〒132-0014　江戸川区東瑞江1丁目17番1号) <br />
               ※都営新宿線 「{% trans 'mizue st' %} 」{% trans 'on foot' %}5{% trans 'minuites' %}<br />
               駅近。無料駐車場有。男女別更衣室。稽古場までエレベーター利用可 <br />
               <br />
               {% trans 'enrollment fee' %}：2000{% trans 'yen' %}, {% trans 'monthly tuition' %}:5000{% trans 'yen' %}、
               スポーツ保険({% trans 'yearly' %})：1850{% trans 'yen' %}(子供800{% trans 'yen' %}),
               {% trans 'uniform charge' %}: 4500{% trans 'yen' %}(子供4000{% trans 'yen' %})<br />
               ★★{% trans 'edogawaclubs' %}{% trans 'training scene' %}★★<br />
               <img src="{{ STATIC_URL }}img/edogawa.jpg" width="580" height="109" />
            </td>
         </tr>
      </table>
   </div>
   <!-- コンテンツ内部 終わり -->
{% endblock %}

entries/templates/pages/links.html
{% extends "base.html" %}
{% block main %}
  <!-- コンテンツ内部 -->
  <div id="contents">
    <img src="{{ STATIC_URL }}img/tkdban.jpg" width="580" height="200" /><br />
    <br />
    {% load i18n %}
    <h2>{% trans 'links' %}</h2>
    <p><a href="http://www.j-taekwondo.com/" target="_blank">ジャパンテコンドースクール</a> 
      ： 東京・横浜で活動するWTFテコンドー教室<br />
      <a href="http://www.taekwondo.vc/" target="_blank">ヨンソン・テコンドー</a> ： 千葉・船橋で活動するWTFテコンドー教室<br />
      <a href="http://www.kakutospirit.net/" target="_blank">格闘スピリット.NET</a> 
      : 格闘技情報サイト<br />
      <a href="http://www.ryujin-jp.net/" target="_blank">格闘技道場一発検索</a> : 格闘技道場検索サイト<br />
      <a href="http://www.sports-ranking.com/" target="_blank">スポーツランキング.com</a> 
      : スポーツ施設検索サイト<br />
      <a href="http://www.tkdshop.jp/" target="_blank">テコンドーオンライン</a> : テコンドー用品専門ショップ<br />
      <a href="http://www.worldchamp.jp/" target="_blank">ワールドチャンプ</a> : 各種格闘技用品販売<br />
    </p>
  </div>
  <!-- コンテンツ内部 終わり -->
{% endblock %}

entries/templates/pages/mail.html
{% extends "base.html" %}
{% block main %}
  <!-- コンテンツ内部 -->
  <div id="contents">
    <img src="{{ STATIC_URL }}img/tkdban.jpg" width="580" height="200" /><br />
    <br />
    {% load i18n %}
    <h2>{% trans 'inquiry' %}</h2>
    <p>{% trans 'staff' %}：{% trans 'kadowaki haruka' %}<br />
      ms-tkd@hotmail.co.jp<br />
      090-4547-6731<br />
      {% trans 'mail explanation1' %}<br />
      {% trans 'mail explanation2' %}<br />
      {% trans 'mail explanation3' %}<br />
    </p>
  </div>
  <!-- コンテンツ内部 終わり -->
{% endblock %}

entries/templates/pages/master.html
{% extends "base.html" %}
{% block main %}
  <!-- コンテンツ内部 -->
  <div id="contents">
    <img src="{{ STATIC_URL }}img/tkdban.jpg" width="580" height="200" /><br />
    <br />
    {% load i18n %}
    <h2>{% trans 'masterintro' %}</h2>
    <p>{% trans 'kwon dohyong' %}　(KWON DOHYONG)<br />
      ・ミョンソンテコンドー師範<br />
      ・世界テコンドー連盟国際師範５段<br />
      <br />
      ２００８年　啓明大学テコンドー学科卒業<br />
      ２００８年～２００９年　韓国天地道場師範<br />
      ２００９年～２０１１年　ジャパンテコンドースクール師範<br />
    </p>
  </div>
  <!-- コンテンツ内部 終わり -->
{% endblock %}